# Generated by Django 2.2.2 on 2019-11-28 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('hobbies', models.TextField(max_length=80)),
                ('nok1_name', models.CharField(max_length=32)),
                ('nok1_phone', models.CharField(max_length=11)),
                ('nok1_relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('sister', 'Sister'), ('uncle', 'Uncle')], max_length=12)),
                ('nok2_name', models.CharField(max_length=32)),
                ('nok2_phone', models.CharField(max_length=11)),
                ('nok2_relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('sister', 'Sister'), ('uncle', 'Uncle')], max_length=12)),
                ('primary', models.CharField(max_length=80)),
                ('secondary', models.CharField(max_length=80)),
                ('tertiary', models.CharField(max_length=80)),
                ('passport', models.ImageField(upload_to='passport')),
                ('o_level', models.ImageField(upload_to='o_level')),
                ('birth_cert', models.ImageField(upload_to='birth_cert')),
                ('indegeneship_cert', models.ImageField(upload_to='indegene')),
                ('degree_cert', models.ImageField(upload_to='degree')),
                ('ref1_name', models.CharField(max_length=35)),
                ('ref1_phone', models.CharField(max_length=11)),
                ('ref1_occupation', models.CharField(max_length=35)),
                ('ref2_name', models.CharField(max_length=35)),
                ('ref2_phone', models.CharField(max_length=11)),
                ('ref2_occupation', models.CharField(max_length=35)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_name',),
            },
        ),
    ]
