# Generated by Django 2.2.2 on 2019-11-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0002_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
