# Generated by Django 2.2.2 on 2019-11-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0003_bio_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='submitted',
            field=models.BooleanField(),
        ),
    ]
