# Generated by Django 2.2.2 on 2019-11-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0004_auto_20191128_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
