# Generated by Django 2.2.2 on 2019-12-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0006_bio_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='email_confirmed',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
